CREATE DATABASE IF NOT EXISTS schoolDB;
USE schoolDB;
CREATE TABLE users
(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	cpf VARCHAR(14) NOT NULL UNIQUE,
	birthdate VARCHAR(10) NOT NULL,
	address VARCHAR(255) NOT NULL,
	phone VARCHAR(15) NOT NULL,
	usertype VARCHAR(15) NOT NULL,
	password VARCHAR(255) NOT NULL,
	file_name VARCHAR(255) NOT NULL,
	grade VARCHAR(5) NOT NULL
);